config/routes.rb
Rails.application.routes.draw do

  resources :questions  do
    resources :question_votes
    resources :answers do
      resources :answer_votes
    end
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many   :answer_votes
end

app/models/answer_vote.rb
class AnswerVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many   :answers
  has_many   :question_votes
end

app/models/question_vote.rb
class QuestionVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many :question_votes
  has_many :answer_votes

  has_secure_password

  after_initialize :init

  def init
    self.reputation ||= 0
  end

end

app/controllers/answer_votes_controller.rb
class AnswerVotesController < ApplicationController
  def create
    user_upvote = AnswerVote.find_by(user_id: current_user.id, answer_id: params[:answer_id], vote: true)
    user_downvote = AnswerVote.find_by(user_id: current_user.id, answer_id: params[:answer_id], vote: false)

    if user_upvote
      user_upvote.destroy
      redirect_to "/questions/#{params[:question_id]}"
    elsif user_downvote
      user_downvote.destroy
      redirect_to "/questions/#{params[:question_id]}"
    else
      @answer_vote = AnswerVote.new(user_id: current_user.id, answer_id: params[:answer_id], vote: params[:vote])
      if !@answer_vote.save
        p "You fucked up something! Check it out!"
      end
      redirect_to "/questions/#{params[:question_id]}"
    end
  end

  def destroy
    @answer_vote = AnswerVote.find_by(user_id: current_user.id, answer_id: params[:answer_id])
    @answer_vote.destroy
    redirect_to "/questions/#{params[:question_id]}"
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)

    if @answer.save
      redirect_to @question
    else
      p "The data did not save properly"
      redirect_to @question
    end
  end

  private

    def answer_params
      answer = {question_id: params[:question_id], content: params[:answer][:answer][:content], title: params[:answer][:answer][:title]}
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to root_path unless current_user
  end

end

app/controllers/question_votes_controller.rb
class QuestionVotesController < ApplicationController
  def create
    user_upvote = QuestionVote.find_by(user_id: current_user.id, question_id: params[:question_id], vote: true)
    user_downvote = QuestionVote.find_by(user_id: current_user.id, question_id: params[:question_id], vote: false)

    if user_upvote
      user_upvote.destroy
      score = user_upvote.question.question_votes.where(vote: true).count - user_upvote.question.question_votes.where(vote: false).count
      render json: {user_upvote: user_upvote, score: score}
    elsif user_downvote
      user_downvote.destroy
      score = user_downvote.question.question_votes.where(vote: true).count - user_downvote.question.question_votes.where(vote: false).count
      render json: {user_downvote: user_downvote, score: score}
    else
      question_vote = QuestionVote.new(user_id: current_user.id, question_id: params[:question_id], vote: params[:vote])
      if !question_vote.save
        p "You fucked up something! Check it out!"
      end
      score = question_vote.question.question_votes.where(vote: true).count - question_vote.question.question_votes.where(vote: false).count
      render json: {question_vote: question_vote, score: score}
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @question_vote = QuestionVote.find_by(user_id: params[:user_id], question_id: params[:question_id])
    @quote = HTTParty.get("https://api.github.com/zen")

    if @quote.response["status"] == "403 Forbidden"
      @quote = "Get out."
    end

  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answer.question_id = @question.id
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      render partial: "question_list", locals: { question: @question }
    else
      render 'new'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    question = Question.find(params[:id])
    question.update_attributes(question_params)
    redirect_to question
  end

  private

    def question_params
      params.require(:question).permit(:title, :content, :user_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to root_path
    end

  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :email, :first_name, :last_name)
    end
end

app/helpers/answer_votes_helper.rb
module AnswerVotesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_votes_helper.rb
module QuestionVotesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>DbcOverflow</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="debug">
      <% if current_user %>
        <div class="debug float-right">Signed in as <%= current_user.username %> | <%= link_to "Logout", '/logout' %></div>
      <% else %>
        <p class="debug float-right"> You are not signed in </p>
      <% end %>
    </header>

    <script src="js/main.js"></script>

    <%= yield %>

  </body>
</html>

app/views/questions/_answer_list.html.erb
<li class="answer-item"><%= answer.title %></li>
<%= link_to 'Upvote', question_answer_answer_votes_path(answer_id: answer.id, question_id: params[:id], vote: true), class: "answer-upvote-link" %>
<%= link_to 'Downvote', question_answer_answer_votes_path(answer_id: answer.id, question_id: params[:id], vote: false ), class: "answer-downvote-link" %>

<p>Score: <%= answer.answer_votes.where(vote: true).count - answer.answer_votes.where(vote: false).count %></p>

app/views/questions/_question_list.html.erb
<div class="question-item">
  <div class="col span-2-t">
    <%= link_to 'Upvote', question_question_votes_path(question.id, vote: true), class: "upvote-link" %>
    <%= link_to 'Downvote', question_question_votes_path(question.id, vote: false ), class: "downvote-link" %>
    <p>Score: <%= question.question_votes.where(vote: true).count - question.question_votes.where(vote: false).count %></p>
  </div>
  <div class="col span-8-t">
    <h2><%= question.title %></h2>
  </div>
  <div class="col span-2-t">
    <p>Ads</p>
  </div>
</div>

app/views/questions/edit.html.erb
<%= form_for :question, url: question_path, method: :patch do |f| %>
  <p><%=f.label :title %><br>
  <%= f.text_field :title, value: @question.title %></p>

  <p><%= f.label :content %><br>
  <%= f.text_area :content, value: @question.content %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/questions/index.html.erb
<% if !current_user %>
  <div class="debug">
    <div class="debug">
      <h1>Signup!</h1>

      <%= form_for :user, url: users_path do |f| %>

        Username: <%= f.text_field :username %>
        Password: <%= f.password_field :password %>
        Password Confirmation: <%= f.password_field :password_confirmation %>
        Email: <%= f.text_field :email %>
        First Name: <%= f.text_field :first_name %>
        Last Name: <%= f.text_field :last_name %>
        <%= f.submit "Submit" %>

      <% end %>
    </div>

    <div class="debug">
      <h1>Login</h1>

      <%= form_tag '/login' do %>

        Username: <%= text_field_tag :username %>
        Password: <%= password_field_tag :password %>
        <%= submit_tag "Submit" %>

      <% end %>
    </div>
  </div>
<% end %>

<h1>Questions Index</h1>

<div class="list-of-questions">
  <% if current_user %>
    <h3 class="col span-8-t debug padding-md clear-both"><%= @quote %></h3>
    <% @questions.each do |question| %>
      <%= render partial: "question_list", locals: { question: question } %>
    <% end %>
  <% else %>
    <h3>Log In Fuccboi</h3>
  <% end %>
</div>

<h3>Post New Question</h3>
<%= form_for :question, url: questions_path, :html => {:class => "questionForm"} do |f| %>
  <p>
    <%=f.label :title %><br>
    <%= f.text_field :title, :class => "title-field" %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => "content-field" %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<%= link_to 'Edit', edit_question_path,
              method: :get %>

<%= link_to 'Destroy', @question,
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

<ul class="list-of-answers">
  <% if current_user %>
    <% @question.answers.each do |answer| %>
      <%= render partial: "answer_list", locals: { answer: answer } %>
    <% end %>
  <% else %>
    <h3>Log In Fuccboi</h3>
  <% end %>
</ul>

<h3>Post New Answer</h3>
<%= form_for [@question, @answer], url: question_answers_path(@question), :html => {:class => "answerForm"} do |f| %>
  <%= f.fields_for @answer do |l| %>
    <p><%=l.label :title %><br>
    <%= l.text_field :title, :class => "answer-title-field" %></p>
    <p><%= l.label :content %><br>
    <%= l.text_area :content, :class => "answer-content-field" %></p>
    <p><%= l.submit %></p>
  <% end %>
<% end %>